#!/bin/sh
#
# PROVIDE: adminer
# REQUIRE: networking
# KEYWORD: 
 
. /etc/rc.subr
 
name="adminer"
rcvar="adminer_enable"
command="/usr/local/bin/php -S localhost:8000 -t /usr/local/www/adminer/"
pidfile="/var/run/${name}.pid"
 
start_cmd="adminer_start"
stop_cmd="adminer_stop"
status_cmd="adminer_status"

adminer_start() {
        /usr/sbin/daemon -P ${pidfile} -r -f  $command
}

adminer_stop() {
        if [ -e "${pidfile}" ]; then
                kill -s TERM `cat ${pidfile}`
        else
                echo "${name} is not running"
        fi

}

adminer_status() {
        if [ -e "${pidfile}" ]; then
                echo "${name} is running as pid `cat ${pidfile}`"
        else
                echo "${name} is not running"
        fi
}
 
load_rc_config $name
: ${goprogram_enable:=no}
 
run_rc_command "$1"
